#!/bin/bash

#PBS -q normal
#PBS -l nodes=1:ppn=8
#PBS -l walltime=48:00:00
#PBS -N patagona-indexindivbams
#PBS -m ae
#PBS -M williamson@unm.edu

cd $PBS_O_WORKDIR
module load miniconda3/4.10.3-an4v
module load parallel/20210922-cfec
eval "$(conda shell.bash hook)"
conda activate uce-env
source $(which env_parallel.bash)

## Index individual bams with a loop
while read sample; do
    samtools index /users/jlwill/wheeler-scratch/patagona/UCE/bams-UCE-singleref/${sample}-aln_dedup.bam
done < /users/jlwill/wheeler-scratch/patagona/UCE/sample_list_seqcap

